image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production
pages:
  script:
  - cd themes/docsy && git submodule update -f --init && cd ../.. && hugo 
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
